// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="runLayer_runLayer,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=0,HLS_SYN_FF=1847,HLS_SYN_LUT=2319,HLS_VERSION=2021_2}" *)

module runLayer (
        ap_local_block,
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 25'd1;
parameter    ap_ST_fsm_state2 = 25'd2;
parameter    ap_ST_fsm_state3 = 25'd4;
parameter    ap_ST_fsm_state4 = 25'd8;
parameter    ap_ST_fsm_state5 = 25'd16;
parameter    ap_ST_fsm_state6 = 25'd32;
parameter    ap_ST_fsm_state7 = 25'd64;
parameter    ap_ST_fsm_state8 = 25'd128;
parameter    ap_ST_fsm_state9 = 25'd256;
parameter    ap_ST_fsm_state10 = 25'd512;
parameter    ap_ST_fsm_state11 = 25'd1024;
parameter    ap_ST_fsm_state12 = 25'd2048;
parameter    ap_ST_fsm_state13 = 25'd4096;
parameter    ap_ST_fsm_state14 = 25'd8192;
parameter    ap_ST_fsm_state15 = 25'd16384;
parameter    ap_ST_fsm_state16 = 25'd32768;
parameter    ap_ST_fsm_state17 = 25'd65536;
parameter    ap_ST_fsm_state18 = 25'd131072;
parameter    ap_ST_fsm_state19 = 25'd262144;
parameter    ap_ST_fsm_state20 = 25'd524288;
parameter    ap_ST_fsm_state21 = 25'd1048576;
parameter    ap_ST_fsm_state22 = 25'd2097152;
parameter    ap_ST_fsm_state23 = 25'd4194304;
parameter    ap_ST_fsm_state24 = 25'd8388608;
parameter    ap_ST_fsm_state25 = 25'd16777216;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 9;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

output   ap_local_block;
input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

wire   [0:0] ap_local_deadlock;
 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [24:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] input_r;
reg   [6:0] output_r_address0;
reg    output_r_ce0;
reg    output_r_we0;
reg   [15:0] output_r_d0;
wire   [15:0] output_r_q0;
wire   [63:0] weights;
wire   [63:0] bias;
wire   [15:0] numOfInNeurons;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state12;
reg   [15:0] numOfInNeurons_read_reg_370;
reg   [63:0] weights_read_reg_380;
reg   [62:0] trunc_ln_reg_391;
reg   [62:0] trunc_ln1_reg_397;
wire   [31:0] conv4_fu_263_p1;
reg   [31:0] conv4_reg_407;
wire    ap_CS_fsm_state10;
wire   [22:0] zext_ln26_fu_266_p1;
reg   [22:0] zext_ln26_reg_412;
wire   [0:0] empty_24_fu_269_p2;
reg   [0:0] empty_24_reg_417;
wire   [22:0] add_ln24_fu_280_p2;
reg   [22:0] add_ln24_reg_424;
wire    ap_CS_fsm_state11;
wire   [7:0] outNeurons_2_fu_291_p2;
reg   [7:0] outNeurons_2_reg_432;
reg   [62:0] p_cast_reg_437;
wire   [0:0] icmp_ln24_fu_285_p2;
wire   [63:0] idxprom17_fu_334_p1;
reg   [63:0] idxprom17_reg_448;
wire    ap_CS_fsm_state20;
reg   [6:0] output_r_addr_reg_454;
reg   [15:0] output_r_load_reg_459;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state23;
reg   [6:0] output_r_addr_1_reg_469;
wire   [15:0] tmp_bias_q0;
reg   [15:0] tmp_bias_load_reg_474;
wire    ap_CS_fsm_state24;
reg   [6:0] tmp_weights_address0;
reg    tmp_weights_ce0;
reg    tmp_weights_we0;
wire   [15:0] tmp_weights_q0;
reg   [6:0] tmp_bias_address0;
reg    tmp_bias_ce0;
reg    tmp_bias_we0;
wire    grp_runLayer_Pipeline_1_fu_193_ap_start;
wire    grp_runLayer_Pipeline_1_fu_193_ap_done;
wire    grp_runLayer_Pipeline_1_fu_193_ap_idle;
wire    grp_runLayer_Pipeline_1_fu_193_ap_ready;
wire    grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWVALID;
wire   [63:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWADDR;
wire   [0:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWID;
wire   [31:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWLEN;
wire   [2:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWSIZE;
wire   [1:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWBURST;
wire   [1:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWLOCK;
wire   [3:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWCACHE;
wire   [2:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWPROT;
wire   [3:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWQOS;
wire   [3:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWREGION;
wire   [0:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWUSER;
wire    grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_WVALID;
wire   [15:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_WDATA;
wire   [1:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_WSTRB;
wire    grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_WLAST;
wire   [0:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_WID;
wire   [0:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_WUSER;
wire    grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARVALID;
wire   [63:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARADDR;
wire   [0:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARID;
wire   [31:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARLEN;
wire   [2:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARSIZE;
wire   [1:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARBURST;
wire   [1:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARLOCK;
wire   [3:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARCACHE;
wire   [2:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARPROT;
wire   [3:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARQOS;
wire   [3:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARREGION;
wire   [0:0] grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARUSER;
wire    grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_RREADY;
wire    grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_BREADY;
wire   [6:0] grp_runLayer_Pipeline_1_fu_193_tmp_bias_address0;
wire    grp_runLayer_Pipeline_1_fu_193_tmp_bias_ce0;
wire    grp_runLayer_Pipeline_1_fu_193_tmp_bias_we0;
wire   [15:0] grp_runLayer_Pipeline_1_fu_193_tmp_bias_d0;
wire    grp_runLayer_Pipeline_2_fu_201_ap_start;
wire    grp_runLayer_Pipeline_2_fu_201_ap_done;
wire    grp_runLayer_Pipeline_2_fu_201_ap_idle;
wire    grp_runLayer_Pipeline_2_fu_201_ap_ready;
wire    grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWVALID;
wire   [63:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWADDR;
wire   [0:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWID;
wire   [31:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWLEN;
wire   [2:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWSIZE;
wire   [1:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWBURST;
wire   [1:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWLOCK;
wire   [3:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWCACHE;
wire   [2:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWPROT;
wire   [3:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWQOS;
wire   [3:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWREGION;
wire   [0:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWUSER;
wire    grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_WVALID;
wire   [15:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_WDATA;
wire   [1:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_WSTRB;
wire    grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_WLAST;
wire   [0:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_WID;
wire   [0:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_WUSER;
wire    grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARVALID;
wire   [63:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARADDR;
wire   [0:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARID;
wire   [31:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARLEN;
wire   [2:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARSIZE;
wire   [1:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARBURST;
wire   [1:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARLOCK;
wire   [3:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARCACHE;
wire   [2:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARPROT;
wire   [3:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARQOS;
wire   [3:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARREGION;
wire   [0:0] grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARUSER;
wire    grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_RREADY;
wire    grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_BREADY;
wire   [6:0] grp_runLayer_Pipeline_2_fu_201_tmp_weights_address0;
wire    grp_runLayer_Pipeline_2_fu_201_tmp_weights_ce0;
wire    grp_runLayer_Pipeline_2_fu_201_tmp_weights_we0;
wire   [15:0] grp_runLayer_Pipeline_2_fu_201_tmp_weights_d0;
wire    grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_start;
wire    grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_done;
wire    grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_idle;
wire    grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_ready;
wire    grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWVALID;
wire   [63:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWADDR;
wire   [0:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWID;
wire   [31:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWLEN;
wire   [2:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWSIZE;
wire   [1:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWBURST;
wire   [1:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWLOCK;
wire   [3:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWCACHE;
wire   [2:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWPROT;
wire   [3:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWQOS;
wire   [3:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWREGION;
wire   [0:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWUSER;
wire    grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_WVALID;
wire   [15:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_WDATA;
wire   [1:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_WSTRB;
wire    grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_WLAST;
wire   [0:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_WID;
wire   [0:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_WUSER;
wire    grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARVALID;
wire   [63:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARADDR;
wire   [0:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARID;
wire   [31:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARLEN;
wire   [2:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARSIZE;
wire   [1:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARBURST;
wire   [1:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARLOCK;
wire   [3:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARCACHE;
wire   [2:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARPROT;
wire   [3:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARQOS;
wire   [3:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARREGION;
wire   [0:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARUSER;
wire    grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_RREADY;
wire    grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_BREADY;
wire   [6:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_tmp_weights_address0;
wire    grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_tmp_weights_ce0;
wire   [15:0] grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_conv205_out;
wire    grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_conv205_out_ap_vld;
wire    gmem_AWREADY;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [0:0] gmem_ARID;
reg   [31:0] gmem_ARLEN;
reg   [2:0] gmem_ARSIZE;
reg   [1:0] gmem_ARBURST;
reg   [1:0] gmem_ARLOCK;
reg   [3:0] gmem_ARCACHE;
reg   [2:0] gmem_ARPROT;
reg   [3:0] gmem_ARQOS;
reg   [3:0] gmem_ARREGION;
reg   [0:0] gmem_ARUSER;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [15:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [9:0] gmem_RFIFONUM;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
reg    grp_runLayer_Pipeline_1_fu_193_ap_start_reg;
wire    ap_CS_fsm_state9;
reg    grp_runLayer_Pipeline_2_fu_201_ap_start_reg;
wire    ap_CS_fsm_state18;
reg   [24:0] ap_NS_fsm;
wire    ap_NS_fsm_state19;
wire    ap_CS_fsm_state19;
reg    grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_start_reg;
wire    ap_CS_fsm_state22;
wire  signed [63:0] sext_ln22_fu_253_p1;
wire  signed [63:0] p_cast_cast_fu_324_p1;
reg   [22:0] phi_mul_fu_104;
reg   [7:0] outNeurons_fu_108;
reg    ap_block_state20_on_subcall_done;
wire    ap_CS_fsm_state25;
wire   [15:0] add_ln32_fu_350_p2;
wire   [23:0] shl_ln_fu_297_p3;
wire   [63:0] zext_ln26_1_fu_305_p1;
wire   [63:0] add_ln26_fu_309_p2;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 25'd1;
#0 grp_runLayer_Pipeline_1_fu_193_ap_start_reg = 1'b0;
#0 grp_runLayer_Pipeline_2_fu_201_ap_start_reg = 1'b0;
#0 grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_start_reg = 1'b0;
end

runLayer_tmp_weights_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
tmp_weights_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(tmp_weights_address0),
    .ce0(tmp_weights_ce0),
    .we0(tmp_weights_we0),
    .d0(grp_runLayer_Pipeline_2_fu_201_tmp_weights_d0),
    .q0(tmp_weights_q0)
);

runLayer_tmp_weights_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
tmp_bias_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(tmp_bias_address0),
    .ce0(tmp_bias_ce0),
    .we0(tmp_bias_we0),
    .d0(grp_runLayer_Pipeline_1_fu_193_tmp_bias_d0),
    .q0(tmp_bias_q0)
);

runLayer_runLayer_Pipeline_1 grp_runLayer_Pipeline_1_fu_193(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_runLayer_Pipeline_1_fu_193_ap_start),
    .ap_done(grp_runLayer_Pipeline_1_fu_193_ap_done),
    .ap_idle(grp_runLayer_Pipeline_1_fu_193_ap_idle),
    .ap_ready(grp_runLayer_Pipeline_1_fu_193_ap_ready),
    .m_axi_gmem_AWVALID(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(gmem_RLAST),
    .m_axi_gmem_RID(gmem_RID),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(gmem_RUSER),
    .m_axi_gmem_RRESP(gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .sext_ln22(trunc_ln_reg_391),
    .tmp_bias_address0(grp_runLayer_Pipeline_1_fu_193_tmp_bias_address0),
    .tmp_bias_ce0(grp_runLayer_Pipeline_1_fu_193_tmp_bias_ce0),
    .tmp_bias_we0(grp_runLayer_Pipeline_1_fu_193_tmp_bias_we0),
    .tmp_bias_d0(grp_runLayer_Pipeline_1_fu_193_tmp_bias_d0)
);

runLayer_runLayer_Pipeline_2 grp_runLayer_Pipeline_2_fu_201(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_runLayer_Pipeline_2_fu_201_ap_start),
    .ap_done(grp_runLayer_Pipeline_2_fu_201_ap_done),
    .ap_idle(grp_runLayer_Pipeline_2_fu_201_ap_idle),
    .ap_ready(grp_runLayer_Pipeline_2_fu_201_ap_ready),
    .m_axi_gmem_AWVALID(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(gmem_RLAST),
    .m_axi_gmem_RID(gmem_RID),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(gmem_RUSER),
    .m_axi_gmem_RRESP(gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .p_cast_cast(p_cast_reg_437),
    .tmp_weights_address0(grp_runLayer_Pipeline_2_fu_201_tmp_weights_address0),
    .tmp_weights_ce0(grp_runLayer_Pipeline_2_fu_201_tmp_weights_ce0),
    .tmp_weights_we0(grp_runLayer_Pipeline_2_fu_201_tmp_weights_we0),
    .tmp_weights_d0(grp_runLayer_Pipeline_2_fu_201_tmp_weights_d0),
    .conv5(numOfInNeurons_read_reg_370)
);

runLayer_runLayer_Pipeline_VITIS_LOOP_28_2 grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_start),
    .ap_done(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_done),
    .ap_idle(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_idle),
    .ap_ready(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_ready),
    .m_axi_gmem_AWVALID(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(gmem_RLAST),
    .m_axi_gmem_RID(gmem_RID),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(gmem_RUSER),
    .m_axi_gmem_RRESP(gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .output_r_load(output_r_load_reg_459),
    .sext_ln28(trunc_ln1_reg_397),
    .numOfInNeurons_cast1(numOfInNeurons_read_reg_370),
    .tmp_weights_address0(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_tmp_weights_address0),
    .tmp_weights_ce0(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_tmp_weights_ce0),
    .tmp_weights_q0(tmp_weights_q0),
    .conv4(numOfInNeurons_read_reg_370),
    .conv205_out(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_conv205_out),
    .conv205_out_ap_vld(grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_conv205_out_ap_vld)
);

runLayer_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_r(input_r),
    .weights(weights),
    .bias(bias),
    .numOfInNeurons(numOfInNeurons),
    .output_r_address0(output_r_address0),
    .output_r_ce0(output_r_ce0),
    .output_r_we0(output_r_we0),
    .output_r_d0(output_r_d0),
    .output_r_q0(output_r_q0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_local_deadlock(ap_local_deadlock)
);

runLayer_gmem_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 16 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .USER_RFIFONUM_WIDTH( 10 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARID(gmem_ARID),
    .I_ARLEN(gmem_ARLEN),
    .I_ARSIZE(gmem_ARSIZE),
    .I_ARLOCK(gmem_ARLOCK),
    .I_ARCACHE(gmem_ARCACHE),
    .I_ARQOS(gmem_ARQOS),
    .I_ARPROT(gmem_ARPROT),
    .I_ARUSER(gmem_ARUSER),
    .I_ARBURST(gmem_ARBURST),
    .I_ARREGION(gmem_ARREGION),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_RID(gmem_RID),
    .I_RUSER(gmem_RUSER),
    .I_RRESP(gmem_RRESP),
    .I_RLAST(gmem_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(16'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(2'd0),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem_BRESP),
    .I_BID(gmem_BID),
    .I_BUSER(gmem_BUSER)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_runLayer_Pipeline_1_fu_193_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_runLayer_Pipeline_1_fu_193_ap_start_reg <= 1'b1;
        end else if ((grp_runLayer_Pipeline_1_fu_193_ap_ready == 1'b1)) begin
            grp_runLayer_Pipeline_1_fu_193_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_runLayer_Pipeline_2_fu_201_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state19) & (1'b1 == ap_CS_fsm_state18))) begin
            grp_runLayer_Pipeline_2_fu_201_ap_start_reg <= 1'b1;
        end else if ((grp_runLayer_Pipeline_2_fu_201_ap_ready == 1'b1)) begin
            grp_runLayer_Pipeline_2_fu_201_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_start_reg <= 1'b1;
        end else if ((grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_ready == 1'b1)) begin
            grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        outNeurons_fu_108 <= 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        outNeurons_fu_108 <= outNeurons_2_reg_432;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_mul_fu_104 <= 23'd0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        phi_mul_fu_104 <= add_ln24_reg_424;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        add_ln24_reg_424 <= add_ln24_fu_280_p2;
        outNeurons_2_reg_432 <= outNeurons_2_fu_291_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        conv4_reg_407[15 : 0] <= conv4_fu_263_p1[15 : 0];
        empty_24_reg_417 <= empty_24_fu_269_p2;
        zext_ln26_reg_412[15 : 0] <= zext_ln26_fu_266_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        idxprom17_reg_448[7 : 0] <= idxprom17_fu_334_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        numOfInNeurons_read_reg_370 <= numOfInNeurons;
        trunc_ln1_reg_397 <= {{input_r[63:1]}};
        trunc_ln_reg_391 <= {{bias[63:1]}};
        weights_read_reg_380 <= weights;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        output_r_addr_1_reg_469 <= idxprom17_reg_448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state20) & (empty_24_reg_417 == 1'd0))) begin
        output_r_addr_reg_454 <= idxprom17_fu_334_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        output_r_load_reg_459 <= output_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln24_fu_285_p2 == 1'd0) & (empty_24_reg_417 == 1'd0))) begin
        p_cast_reg_437 <= {{add_ln26_fu_309_p2[63:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        tmp_bias_load_reg_474 <= tmp_bias_q0;
    end
end

always @ (*) begin
    if ((grp_runLayer_Pipeline_1_fu_193_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state20_on_subcall_done)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

always @ (*) begin
    if ((grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_done == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln24_fu_285_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln24_fu_285_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (gmem_ARREADY == 1'b1))) begin
        gmem_ARADDR = p_cast_cast_fu_324_p1;
    end else if (((1'b1 == ap_CS_fsm_state2) & (gmem_ARREADY == 1'b1))) begin
        gmem_ARADDR = sext_ln22_fu_253_p1;
    end else if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem_ARADDR = grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state20) & (empty_24_reg_417 == 1'd0)))) begin
        gmem_ARADDR = grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARADDR = grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem_ARBURST = grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARBURST;
    end else if (((1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state20) & (empty_24_reg_417 == 1'd0)))) begin
        gmem_ARBURST = grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARBURST;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARBURST = grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARBURST;
    end else begin
        gmem_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem_ARCACHE = grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARCACHE;
    end else if (((1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state20) & (empty_24_reg_417 == 1'd0)))) begin
        gmem_ARCACHE = grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARCACHE;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARCACHE = grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARCACHE;
    end else begin
        gmem_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem_ARID = grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARID;
    end else if (((1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state20) & (empty_24_reg_417 == 1'd0)))) begin
        gmem_ARID = grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARID;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARID = grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARID;
    end else begin
        gmem_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (gmem_ARREADY == 1'b1))) begin
        gmem_ARLEN = conv4_reg_407;
    end else if (((1'b1 == ap_CS_fsm_state2) & (gmem_ARREADY == 1'b1))) begin
        gmem_ARLEN = 32'd128;
    end else if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem_ARLEN = grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state20) & (empty_24_reg_417 == 1'd0)))) begin
        gmem_ARLEN = grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARLEN = grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem_ARLOCK = grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARLOCK;
    end else if (((1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state20) & (empty_24_reg_417 == 1'd0)))) begin
        gmem_ARLOCK = grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARLOCK;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARLOCK = grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARLOCK;
    end else begin
        gmem_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem_ARPROT = grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARPROT;
    end else if (((1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state20) & (empty_24_reg_417 == 1'd0)))) begin
        gmem_ARPROT = grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARPROT;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARPROT = grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARPROT;
    end else begin
        gmem_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem_ARQOS = grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARQOS;
    end else if (((1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state20) & (empty_24_reg_417 == 1'd0)))) begin
        gmem_ARQOS = grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARQOS;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARQOS = grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARQOS;
    end else begin
        gmem_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem_ARREGION = grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARREGION;
    end else if (((1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state20) & (empty_24_reg_417 == 1'd0)))) begin
        gmem_ARREGION = grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARREGION;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARREGION = grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARREGION;
    end else begin
        gmem_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem_ARSIZE = grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARSIZE;
    end else if (((1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state20) & (empty_24_reg_417 == 1'd0)))) begin
        gmem_ARSIZE = grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARSIZE;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARSIZE = grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARSIZE;
    end else begin
        gmem_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem_ARUSER = grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARUSER;
    end else if (((1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state20) & (empty_24_reg_417 == 1'd0)))) begin
        gmem_ARUSER = grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARUSER;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARUSER = grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARUSER;
    end else begin
        gmem_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state12) & (gmem_ARREADY == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (gmem_ARREADY == 1'b1)))) begin
        gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem_ARVALID = grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state20) & (empty_24_reg_417 == 1'd0)))) begin
        gmem_ARVALID = grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARVALID = grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem_RREADY = grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state20) & (empty_24_reg_417 == 1'd0)))) begin
        gmem_RREADY = grp_runLayer_Pipeline_2_fu_201_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_RREADY = grp_runLayer_Pipeline_1_fu_193_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24))) begin
        output_r_address0 = output_r_addr_1_reg_469;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        output_r_address0 = output_r_addr_reg_454;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        output_r_address0 = idxprom17_fu_334_p1;
    end else begin
        output_r_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | ((1'b1 == ap_CS_fsm_state20) & (1'b0 == ap_block_state20_on_subcall_done)))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        output_r_d0 = add_ln32_fu_350_p2;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        output_r_d0 = grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_conv205_out;
    end else begin
        output_r_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | ((1'b1 == ap_CS_fsm_state23) & (empty_24_reg_417 == 1'd0)))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        tmp_bias_address0 = idxprom17_reg_448;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        tmp_bias_address0 = grp_runLayer_Pipeline_1_fu_193_tmp_bias_address0;
    end else begin
        tmp_bias_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        tmp_bias_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        tmp_bias_ce0 = grp_runLayer_Pipeline_1_fu_193_tmp_bias_ce0;
    end else begin
        tmp_bias_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tmp_bias_we0 = grp_runLayer_Pipeline_1_fu_193_tmp_bias_we0;
    end else begin
        tmp_bias_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        tmp_weights_address0 = grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_tmp_weights_address0;
    end else if (((1'b1 == ap_CS_fsm_state20) & (empty_24_reg_417 == 1'd0))) begin
        tmp_weights_address0 = grp_runLayer_Pipeline_2_fu_201_tmp_weights_address0;
    end else begin
        tmp_weights_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        tmp_weights_ce0 = grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_tmp_weights_ce0;
    end else if (((1'b1 == ap_CS_fsm_state20) & (empty_24_reg_417 == 1'd0))) begin
        tmp_weights_ce0 = grp_runLayer_Pipeline_2_fu_201_tmp_weights_ce0;
    end else begin
        tmp_weights_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) & (empty_24_reg_417 == 1'd0))) begin
        tmp_weights_we0 = grp_runLayer_Pipeline_2_fu_201_tmp_weights_we0;
    end else begin
        tmp_weights_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (gmem_ARREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_runLayer_Pipeline_1_fu_193_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln24_fu_285_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln24_fu_285_p2 == 1'd0) & (empty_24_reg_417 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (gmem_ARREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((1'b1 == ap_CS_fsm_state20) & (1'b0 == ap_block_state20_on_subcall_done) & (empty_24_reg_417 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else if (((1'b1 == ap_CS_fsm_state20) & (1'b0 == ap_block_state20_on_subcall_done) & (empty_24_reg_417 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((1'b1 == ap_CS_fsm_state22) & (grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln24_fu_280_p2 = (phi_mul_fu_104 + zext_ln26_reg_412);

assign add_ln26_fu_309_p2 = (zext_ln26_1_fu_305_p1 + weights_read_reg_380);

assign add_ln32_fu_350_p2 = (output_r_q0 + tmp_bias_load_reg_474);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state19 = ap_NS_fsm[32'd18];

always @ (*) begin
    ap_block_state20_on_subcall_done = ((grp_runLayer_Pipeline_2_fu_201_ap_done == 1'b0) & (empty_24_reg_417 == 1'd0));
end

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'd0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign conv4_fu_263_p1 = numOfInNeurons_read_reg_370;

assign empty_24_fu_269_p2 = ((numOfInNeurons_read_reg_370 == 16'd0) ? 1'b1 : 1'b0);

assign grp_runLayer_Pipeline_1_fu_193_ap_start = grp_runLayer_Pipeline_1_fu_193_ap_start_reg;

assign grp_runLayer_Pipeline_2_fu_201_ap_start = grp_runLayer_Pipeline_2_fu_201_ap_start_reg;

assign grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_start = grp_runLayer_Pipeline_VITIS_LOOP_28_2_fu_210_ap_start_reg;

assign icmp_ln24_fu_285_p2 = ((outNeurons_fu_108 == 8'd128) ? 1'b1 : 1'b0);

assign idxprom17_fu_334_p1 = outNeurons_fu_108;

assign outNeurons_2_fu_291_p2 = (outNeurons_fu_108 + 8'd1);

assign p_cast_cast_fu_324_p1 = $signed(p_cast_reg_437);

assign sext_ln22_fu_253_p1 = $signed(trunc_ln_reg_391);

assign shl_ln_fu_297_p3 = {{phi_mul_fu_104}, {1'd0}};

assign zext_ln26_1_fu_305_p1 = shl_ln_fu_297_p3;

assign zext_ln26_fu_266_p1 = numOfInNeurons_read_reg_370;

always @ (posedge ap_clk) begin
    conv4_reg_407[31:16] <= 16'b0000000000000000;
    zext_ln26_reg_412[22:16] <= 7'b0000000;
    idxprom17_reg_448[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
end

endmodule //runLayer
